blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Tunnelsats Telegram Group
    url: https://tunnelsats.com/join-telegram
    about: Ask quick questions or get help with setup in our Telegram community.
  - name: ğŸ” Security Policy
    url: https://github.com/Tunnelsats/tunnelsats/blob/main/SECURITY.md
    about: Please follow the private disclosure process described here for all security issues.
